# Generated by Django 4.0.4 on 2022-05-18 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodd', models.DecimalField(decimal_places=0, max_digits=11)),
                ('numb', models.DecimalField(decimal_places=0, max_digits=11)),
            ],
        ),
    ]
